version: '3'

services:

  toasterservice:
    image: localhost:5000/toasterservice
    deploy:
      replicas: 5
    depends_on: 
      - zookeeper

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181